#!/Bin/bash
#Зайти в папку 
cd /Volumes/Mac/Courses_QA_29/homeWork_29/HW_1
#Создать 3 папки
mkdir Folder1 Folder2 Folder3
#Зайти в любую папку
cd /Volumes/Mac/Courses_QA_29/homeWork_29/HW_1/Folder1
#Создать 5 файлов (3 txt, 2 json)
touch File1.txt File2.txt File3.txt File4.json File5.json
#Создать 3 папки
mkdir dir1 dir2 dir3
#Вывести список содержимого папки
ls -la
#переместить любые 2 файла, которые вы создали, в любую другую папку.
mv file1.txt file2.txt /Volumes/Mac/Courses_QA_29/homeWork_29/HW_1/Folder2